name: dio_speed_tracker_example
description: Example app demonstrating how to use the dio_speed_tracker package
publish_to: 'none' # This prevents accidental publishing

version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  dio_speed_tracker:
    path: ../

  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
