name: dio_speed_tracker
description: "A lightweight and extensible Dio interceptor for monitoring real-world network speed in Mbps, based on actual HTTP download performance. Emits NetworkStatus.poor when the average speed drops below a customizable threshold. Unlike custom_ping, this works in restricted environments without requiring ICMP (ping) support."
version: 0.0.1

homepage: https://github.com/oscarshaitan/dio_speed_tracker
repository: https://github.com/oscarshaitan/dio_speed_tracker
issue_tracker: https://github.com/oscarshaitan/dio_speed_tracker/issues
documentation: https://github.com/oscarshaitan/dio_speed_tracker/blob/master/README.md

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8
  collection: ^1.19.1
  dio: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - network
  - dio
  - performance
  - connection
  - speed

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

flutter:
  plugin:
    platforms:
      android:
        package: com.otigreros.dio_speed_tracker.dio_speed_tracker
        pluginClass: DioSpeedTrackerPlugin
      ios:
        pluginClass: DioSpeedTrackerPlugin
      linux:
        pluginClass: DioSpeedTrackerPlugin
      macos:
        pluginClass: DioSpeedTrackerPlugin
      windows:
        pluginClass: DioSpeedTrackerPluginCApi
      web:
        pluginClass: DioSpeedTrackerWeb
        fileName: dio_speed_tracker_web.dart